### ISSUE TITLE
RADIUS passwords

### ISSUE THREAD

**Issue by jullrey** [WorMzy/vlock#1]
I run several security STIG'd RHEL 7 and 8 sytems that I force users to only authenticate using RADIUS passwords.  I enforce this by deleteing the local password for users.  The STIG I apply wont allow users without passwords to login, but it does allow RADIUS authentication to succed before the system determines they don't have a local password.  On RHEL 8 the STIG'd tmux configuration calls vlock after 900 seconds.  If I don't have a local password I can not unlock vlock.  Does vlock rely on PAM and can it be configured to support RADIUS authentication?

Thanks,

John

**Comment by WorMzy** [comment]
You would be better asking the current upstream of vlock: http://kbd-project.org/

This was just a mirror of the source code as it stood when the original source went offline.
